In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [85]:
df = pd.read_csv("/content/drive/MyDrive/ AI ML/Colab Notebooks/Ecommerce Customers.csv")

In [86]:
df.head(10)

Email  \
0      mstephenson@fernandez.com   
1              hduke@hotmail.com   
2               pallen@yahoo.com   
3        riverarebecca@gmail.com   
4  mstephens@davidson-herman.com   
5         alvareznancy@lucas.biz   
6          katherine20@yahoo.com   
7             awatkins@yahoo.com   
8    vchurch@walter-martinez.com   
9               bonnie69@lin.biz   

                                             Address            Avatar  \
0       835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1     4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2  24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3   1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4  14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   
5  645 Martha Park Apt. 611\nJeffreychester, MN 6...       FloralWhite   
6  68388 Reyes Lights Suite 692\nJosephbury, WV 9...     DarkSlateBlue   
7              Unit 6538 Box 8980\nDPO AP 09026-4941              Aqua   
8             860 Lee Key\nWest Debra, SD 97450-0495            Salmon   
9              PSC 2734, Box 5255\nAPO AA 98456-7482             Brown   

   Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0            34.497268    12.655651        39.577668              4.082621   
1            31.926272    11.109461        37.268959              2.664034   
2            33.000915    11.330278        37.110597              4.104543   
3            34.305557    13.717514        36.721283              3.120179   
4            33.330673    12.795189        37.536653              4.446308   
5            33.871038    12.026925        34.476878              5.493507   
6            32.021596    11.366348        36.683776              4.685017   
7            32.739143    12.351959        37.373359              4.434273   
8            33.987773    13.386235        37.534497              3.273434   
9            31.936549    11.814128        37.145168              3.202806   

   Yearly Amount Spent  
0           587.951054  
1           392.204933  
2           487.547505  
3           581.852344  
4           599.406092  
5           637.102448  
6           521.572175  
7           549.904146  
8           570.200409  
9           427.199385

In [87]:
df.describe()

Avg. Session Length  Time on App  Time on Website  \
count           500.000000   500.000000       500.000000   
mean             33.053194    12.052488        37.060445   
std               0.992563     0.994216         1.010489   
min              29.532429     8.508152        33.913847   
25%              32.341822    11.388153        36.349257   
50%              33.082008    11.983231        37.069367   
75%              33.711985    12.753850        37.716432   
max              36.139662    15.126994        40.005182   

       Length of Membership  Yearly Amount Spent  
count            500.000000           500.000000  
mean               3.533462           499.314038  
std                0.999278            79.314782  
min                0.269901           256.670582  
25%                2.930450           445.038277  
50%                3.533975           498.887875  
75%                4.126502           549.313828  
max                6.922689           765.518462

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Email                 500 non-null    object 
 1   Address               500 non-null    object 
 2   Avatar                500 non-null    object 
 3   Avg. Session Length   500 non-null    float64
 4   Time on App           500 non-null    float64
 5   Time on Website       500 non-null    float64
 6   Length of Membership  500 non-null    float64
 7   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5), object(3)
memory usage: 31.4+ KB


In [89]:
df.isnull().sum()

Email                   0
Address                 0
Avatar                  0
Avg. Session Length     0
Time on App             0
Time on Website         0
Length of Membership    0
Yearly Amount Spent     0
dtype: int64

In [90]:
x = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [91]:
print(x)

[[34.49726773 12.65565115 39.57766802  4.08262063]
 [31.92627203 11.10946073 37.26895887  2.66403418]
 [33.00091476 11.33027806 37.11059744  4.1045432 ]
 ...
 [32.64677668 11.49940906 38.33257633  4.95826447]
 [33.32250105 12.39142299 36.84008573  2.33648467]
 [33.71598092 12.41880832 35.77101619  2.73515957]]


In [92]:
print(y)

[587.95105397 392.20493344 487.54750487 581.85234404 599.40609205
 637.10244792 521.57217476 549.90414611 570.20040896 427.1993849
 492.60601272 522.33740461 408.64035107 573.41586733 470.4527333
 461.7807422  457.84769594 407.70454755 452.31567548 605.0610388
 534.70574381 419.93877484 436.51560573 519.34098913 700.91709162
 423.17999168 619.89563986 486.83893477 529.53766534 554.72208383
 497.5866713  447.68790654 588.71260551 491.07322368 507.44183234
 521.88357317 347.77692663 490.73863214 478.17033405 537.84619527
 532.75178758 501.87443028 591.19717818 547.24434342 448.22982919
 549.86059046 593.91500297 563.67287336 479.73194909 416.35835358
 725.58481406 442.66725174 384.62657157 451.45744687 522.40414126
 483.67330802 520.89879445 453.16950235 496.65070807 547.36514059
 616.85152297 507.212569   613.59932337 483.15972078 540.26340041
 765.51846194 553.60153468 469.3108615  408.62018783 451.57568516
 444.96655165 595.8228367  418.1500811  534.7771881  578.24160506
 478.71935687

In [94]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [96]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(400, 4)
(100, 4)
(400,)
(100,)


In [98]:
print(x_train)

[[ 0.72875642 -0.14037637 -0.17321599  0.06519749]
 [ 1.23367035 -0.23549152 -0.70076461 -1.41309514]
 [-0.44946538  1.93596147  0.16698241  0.48362047]
 ...
 [-1.26587083 -1.17327098 -2.08875055 -0.42804013]
 [-0.81225043  2.07956541  0.00264921  0.18897947]
 [-0.64425634 -0.61010223  0.55038981 -0.95567649]]


In [97]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [99]:
#from sklearn.model_selection import train_test_split # Importing train_test_split from sklearn
from sklearn.tree import DecisionTreeRegressor # Importing DecisionTreeRegressor from sklearn
from sklearn.ensemble import RandomForestRegressor # Importing RandomForestRegressor from sklearn
from sklearn.linear_model import LinearRegression # Importing LinearRegression from sklearn
from sklearn.metrics import mean_squared_error # Importing mean_squared_error from sklearn
import xgboost as xgb # Importing xgboost from xgboost
import lightgbm as lgb # Importing lightgbm from lightgbm
from sklearn.model_selection import GridSearchCV # Importing GridSearchCV from sklearn

/usr/local/lib/python3.11/dist-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)


In [100]:
models = [DecisionTreeRegressor(max_depth=5, random_state=42,
            min_samples_leaf=5, min_samples_split=5),
            LinearRegression(),
            RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42, min_samples_leaf=5, min_samples_split=5),
            GridSearchCV(RandomForestRegressor(random_state=42), param_grid={'n_estimators': [100, 200, 300, 400, 500], 'max_depth': [5, 10, 15, 20, 25]}, cv=5),
            xgb.XGBRegressor(n_estimators=100, max_depth=5, random_state=42, framework_version=1.3),
            GridSearchCV(xgb.XGBRegressor(random_state=42), param_grid={'n_estimators': [100, 200, 300, 400, 500], 'max_depth': [5, 10, 15, 20, 25]}, cv=5),
            lgb.LGBMRegressor(n_estimators=100, max_depth=5, random_state=42),
            GridSearchCV(lgb.LGBMRegressor(random_state=42), param_grid={'n_estimators': [100, 200, 300, 400, 500], 'max_depth': [5, 10, 15, 20, 25]}, cv=5),]

In [101]:
models_short = ["DecisionTreeRegressor", "LinearRegressor", "RandomForestRegressor", "GridSearchCV(RandomForestRegressor)", "xgb.XGBRegressor", "GridSearchCV(xgboost)", "lgb.LGBMRegressor", "GridSearchCV(lightgbm)"]

In [106]:
for i in range(len(models)): # Looping through the models
    models[i].fit(x_train, y_train) # Fitting the model to the train set
    preds_test = models[i].predict(x_test) # Predicting the test set
    #preds_complete = models[i].predict(X1) # Predicting the complete set
    #plot_prediction_vs_datetime(X_tests[0], preds_test, y_tests[0], 'Prediction vs Actual for Junction 1') # Plotting the prediction vs actual values
    train_score = models[i].score(x_train, y_train) # Calculating the score of the train set
    test_score = models[i].score(x_test, y_test) # Calculating the score of the test set
    print(f"Accuracy score (Junction 1) for the model {models_short[i]} on the train set: {train_score}") # Printing the score of the train set
    print(f"Accuracy score (Junction 1) for the model {models_short[i]} on the test set: {test_score}") # Printing the score of the test set
    print(f"RMSE score (Junction 1) for the model {models_short[i]} on the test set: {mean_squared_error(y_test, preds_test)**(1/2)}") # Printing the RMSE score of the test set


Accuracy score (Junction 1) for the model DecisionTreeRegressor on the train set: 0.8911646190308918
Accuracy score (Junction 1) for the model DecisionTreeRegressor on the test set: 0.7714632505453523
RMSE score (Junction 1) for the model DecisionTreeRegressor on the test set: 33.64004275331482
Accuracy score (Junction 1) for the model LinearRegressor on the train set: 0.9854240629700333
Accuracy score (Junction 1) for the model LinearRegressor on the test set: 0.9778130629184126
RMSE score (Junction 1) for the model LinearRegressor on the test set: 10.481590584636482
Accuracy score (Junction 1) for the model RandomForestRegressor on the train set: 0.9432676869070986
Accuracy score (Junction 1) for the model RandomForestRegressor on the test set: 0.8807466184489966
RMSE score (Junction 1) for the model RandomForestRegressor on the test set: 24.300424901261277
Accuracy score (Junction 1) for the model GridSearchCV(RandomForestRegressor) on the train set: 0.9928663169080206
Accuracy scor

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [16:35:42] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "framework_version" } are not used.

  warnings.warn(smsg, UserWarning)


Accuracy score (Junction 1) for the model xgb.XGBRegressor on the train set: 0.9999202849858619
Accuracy score (Junction 1) for the model xgb.XGBRegressor on the test set: 0.9330448156689487
RMSE score (Junction 1) for the model xgb.XGBRegressor on the test set: 18.208351186644705


AttributeError: 'super' object has no attribute '__sklearn_tags__'

In [107]:
from sklearn.linear_model import LinearRegression
ls = LinearRegression()
ls.fit(x_train, y_train)


LinearRegression()

In [108]:
y_pred = ls.predict(x_test)

In [109]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("RMSE:", rmse)

RMSE: 10.481590584636482


In [110]:
print(y_pred)


[402.86230051 542.53325708 426.62011918 501.91386363 409.6666551
 569.92155038 531.50423529 505.94309188 408.10378607 473.45942928
 441.18668812 424.52463471 424.83341694 527.12061508 430.87985533
 423.47062047 575.8751518  484.6563331  457.77896975 481.58742311
 501.56110993 513.12815188 507.49166899 646.63377343 449.70050586
 496.26290484 556.18523776 554.78684161 399.1582784  325.16921284
 532.62732659 477.73025415 500.76491535 305.09971374 505.46811902
 483.52069444 519.09464122 437.75549737 456.25005245 470.63517876
 494.11207805 444.65549239 508.57079732 500.88197484 488.35128728
 535.34025218 594.58301773 513.59474408 279.69877702 432.71590835
 421.06976164 480.94327496 584.59481888 608.61734059 564.42312991
 494.47224504 393.95593318 456.11321352 572.92228417 499.27385693
 512.42973545 391.56170305 479.60705887 481.05023229 474.71926117
 546.37716047 430.11675694 601.91418143 422.26508516 493.11622454
 528.10614863 581.06630842 620.60774498 512.47838603 411.2147464
 498.0709535

In [111]:
print(y_test)

[401.03313522 534.7771881  418.6027421  503.97837905 410.06961106
 557.60826205 538.94197453 514.33655827 408.62018783 475.01540709
 427.1993849  434.02169975 411.18696357 533.51493526 447.3690272
 407.54216801 573.84743772 497.5866713  466.42119882 467.80092437
 510.40138845 510.50147847 511.97985999 640.5840619  444.2859075
 502.77107457 551.62014548 548.51852928 390.10327297 330.59444603
 535.32161009 478.60091594 499.14015245 298.76200786 487.54750487
 498.63559849 512.16586639 444.96655165 468.6684656  483.15972078
 474.53232944 439.07476674 515.50247966 485.92313052 491.07322368
 544.77986372 587.95105397 522.33740461 275.91842065 436.51560573
 418.1500811  493.71919298 573.30622226 608.27181662 545.94549214
 483.67330802 424.18549429 452.31567548 568.71757593 488.78606109
 510.66179222 376.49684072 473.36049557 479.24741678 475.75906779
 537.84619527 436.72055586 593.91500297 421.32663126 503.17508519
 532.12744911 592.6884532  616.66028602 503.21739312 404.82452887
 494.6871558

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTree()
